services:
  db:
    image: postgis/postgis:15-3.4  # <--- This is the GIS version of Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=transport
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123456
    ports:
      - "5432:5432"

  web:
    build: .  # This tells Docker to use your Dockerfile in the current folder
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=transport
      - DB_USER=postgres
      - DB_PASSWORD=qwerty123456
      - DB_HOST=db  # <--- This MUST match the service name above
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: