# Generated by Django 5.2 on 2025-06-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routerun',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='routerun',
            name='start_time',
        ),
    ]
