# Generated by Django 5.2 on 2025-06-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_creator_alter_station_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
